kconfig: Update/Port Gtk flavour to use Gtk3
* Use only non-deprecated functions, use accessor functions instead of
    direct access.
* libglade is deprecated: use GtkBuilder and ui files instead.
* Remove some global variables.
* Use new gtk signals.
* Split code into gconf.c and gconf_treeview_model. gconf.c now
    only contains ui init and ui signal callback code, all tree/model
    code is in the second file.
* Use more icons from the system theme instead of the lowres
    images.c constants.
* Update POTFILES.in

Signed-off-by: David Graeff <david.graeff@web.de>

diff --git a/scripts/kconfig/gconfig/Makefile b/scripts/kconfig/gconfig/Makefile
--- a/scripts/kconfig/gconfig/Makefile
+++ b/scripts/kconfig/gconfig/Makefile
@@ -13,7 +13,7 @@ gconfig: $(obj)/gconf
 #         Based on GTK which needs to be installed to compile it
 # object files used by all kconfig flavours listed above
 
-gconf-objs	:= gconfig/gconf.o zconf.tab.o
+gconf-objs	:= gconfig/gconf.o gconfig/gconf_treeview_model.o zconf.tab.o
 
 ifeq ($(MAKECMDGOALS),gconfig)
 	gconf-target := 1
@@ -25,10 +25,15 @@ endif
 
 clean-files	+= gconfig/gconf.glade.h gconf
 
-
-HOSTLOADLIBES_gconf	= `pkg-config --libs gtk+-2.0 gmodule-2.0 libglade-2.0`
-HOSTCFLAGS_gconf.o	= `pkg-config --cflags gtk+-2.0 gmodule-2.0 libglade-2.0` \
-                          -Wno-missing-prototypes
+HOSTLOADLIBES_gconf	= `pkg-config --libs gtk+-3.0 gmodule-2.0`
+HOSTCFLAGS_gconf.o	= `pkg-config --cflags gtk+-3.0 gmodule-2.0` \
+                          -Wno-missing-prototypes -DGTK_DISABLE_SINGLE_INCLUDES \
+                          -DGDK_DISABLE_DEPRECATED -DGTK_DISABLE_DEPRECATED \
+                          -DGSEAL_ENABLE -std=c99
+HOSTCFLAGS_gconf_treeview_model.o	= `pkg-config --cflags gtk+-3.0 gmodule-2.0` \
+                          -Wno-missing-prototypes -DGTK_DISABLE_SINGLE_INCLUDES \
+                          -DGDK_DISABLE_DEPRECATED -DGTK_DISABLE_DEPRECATED \
+                          -DGSEAL_ENABLE -std=c99
 
 $(obj)/gconfig/gconf.o: $(obj)/gconfig/.tmp_gtkcheck
 
@@ -37,20 +42,20 @@ ifeq ($(gconf-target),1)
 
 # GTK needs some extra effort, too...
 $(obj)/gconfig/.tmp_gtkcheck:
-	@if `pkg-config --exists gtk+-2.0 gmodule-2.0 libglade-2.0`; then		\
-		if `pkg-config --atleast-version=2.0.0 gtk+-2.0`; then			\
+	@if `pkg-config --exists gtk+-3.0`; then		\
+		if `pkg-config --atleast-version=3.0.0 gtk+-3.0`; then			\
 			touch $@;								\
 		else									\
 			echo >&2 "*"; 							\
-			echo >&2 "* GTK+ is present but version >= 2.0.0 is required.";	\
+			echo >&2 "* GTK+ is present but version >= 3.0.0 is required.";	\
 			echo >&2 "*";							\
 			false;								\
 		fi									\
 	else										\
 		echo >&2 "*"; 								\
 		echo >&2 "* Unable to find the GTK+ installation. Please make sure that"; 	\
-		echo >&2 "* the GTK+ 2.0 development package is correctly installed..."; 	\
-		echo >&2 "* You need gtk+-2.0, glib-2.0 and libglade-2.0."; 		\
+		echo >&2 "* the GTK+ 3.0 development package is correctly installed..."; 	\
+		echo >&2 "* You need gtk+-3.0 and glib-2.0."; 		\
 		echo >&2 "*"; 								\
 		false;									\
 	fi
